package com.epam.esm.impl;

public enum SearchType {
    BY_TAG,
    BY_NAME_OR_DESCR_PART,
    BY_TAG_AND_NAME_OR_DESCR_PART,
    ALL,
    BY_TAG_DESCENDING,
    BY_NAME_OR_DESCR_PART_DESCENDING,
    BY_TAG_AND_NAME_OR_DESCR_PART_DESCENDING
}
